require:
  - ./rubocop/cop/metrics/unimafy_method_length.rb
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rake
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.3
  Exclude:
    - '.git/**/*'
    - 'coverage/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'bin/**/*'
Metrics/BlockLength:
  AllowedMethods: ['describe']
  Max: 300
Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false # Use SeliseMethodLength instead

Metrics/UnimafyMethodLength:
  CountComments: false
  Max: 50
  CountAsOne: ['array', 'heredoc']

# Rails automatically detects `inverse_of` association from 4.1 onwards. Although it
# doesn't notify if it fails to infer. If that is noticed, add it and re-enable this.
Rails/InverseOf:
  Enabled: false

# Devs are expected to be aware of methods that don't trigger validations/callbacks.
# `insert_all`, `upsert_all`, `update_columns` etc are used for an improved performance.
Rails/SkipsModelValidations:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - for
    - when
    - with
    - without
    - as

# With swagger, it blocks aren't necessary
RSpec/EmptyExampleGroup:
  Enabled: false

# This is for a special case
#  #=> let(:Authorization) { token(user) }
# where you need to send variable name as 'Authorization'
RSpec/VariableName:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Max: 100

RSpec/ExampleLength:
  Max: 100

Rails/Output:
  Enabled: false


